version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: relay-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=relay
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - relay-network
  app:
    container_name: relay-application
    image: relay-api
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - relay-network
    depends_on:
      - mysql # depends on mysql db initialization
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://relay-db:3306/relay?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=localhost
networks:
  relay-network:
    #    name: relay-network
    driver: bridge # use bridge driver instead of host
