spring:
  application:
    name: relay-api
  main:
    banner-mode: "off"
  profiles:
    active: localhost
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 30
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://relay-db:3306/relay?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1

logging:
  level:
    org.hibernate.SQL: DEBUG

resource:
  path: /relay/api

# Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


